In [8]:
import numpy as np

In [9]:
angka = [1,2,3]

In [10]:
angkanp = np.array(angka)

In [11]:
angka

[1, 2, 3]

In [12]:
angkanp

array([1, 2, 3])

In [13]:
# contoh perbedaan hasil operasi

angka*([2, 2, 2])

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
# contoh perbedaan hasil operasi

angkanp*3

array([3, 6, 9])

In [14]:
list = [[1,2,3],[4,5,6],[7,8,9]]
list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
listnp = np.array(list)
listnp 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.linspace(0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

## Identity Matrix

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# bilangan distribusi uniform (0-1)
np.random.rand(7)

array([0.33589606, 0.29708473, 0.12747754, 0.39230282, 0.93698233,
       0.64339832, 0.8931916 ])

In [27]:
# bilangan distribusi uniform (0-1) matriks 2 dimensi
np.random.rand(5,4)

array([[0.66999304, 0.49022166, 0.71642722, 0.05449983],
       [0.80827147, 0.7555885 , 0.71855208, 0.53005142],
       [0.54999296, 0.69260443, 0.37063212, 0.40952457],
       [0.16346084, 0.63643312, 0.19890285, 0.55310952],
       [0.72006448, 0.96621358, 0.49669322, 0.79249193]])

In [28]:
# bilangan distribusi normal (gaussian)
np.random.randn(10)

array([-0.40114798,  0.15362456, -0.87980916, -0.61153583,  1.00705929,
        0.65084147,  1.87581179, -0.43863839, -0.07057597, -0.15798262])

In [29]:
# bilangan distribusi normal (gaussian)
np.random.randn(4,4)

array([[ 0.43849659, -1.2917441 ,  0.28907883, -0.62872698],
       [ 0.5862704 , -0.48304223, -0.95351158,  0.9236126 ],
       [-0.48873664,  0.11853911, -2.41545125,  0.43484811],
       [-0.09188311,  0.31187827, -1.08618441, -0.30758335]])

In [39]:
from numpy.random import rand, randn, randint

In [32]:
randn(6,2)

array([[ 1.24876424,  0.55637736],
       [ 2.06200654,  1.15695945],
       [-0.50899006, -0.3055891 ],
       [-1.2068578 , -0.54093424],
       [ 1.62477356, -2.35917364],
       [ 0.32560626, -1.35403721]])

In [33]:
randint(0,10)

3

In [34]:
randint(0,10,5)

array([8, 5, 2, 1, 4])

In [36]:
bilangan = randint(0,100,20)

In [37]:
bilangan

array([11, 95, 76, 63, 25, 21, 93, 99,  8, 84,  6, 26,  0, 31, 31, 56, 67,
        8, 97, 21])

In [38]:
#merubah bentuk matriks
bilangan.reshape(4,5)

array([[11, 95, 76, 63, 25],
       [21, 93, 99,  8, 84],
       [ 6, 26,  0, 31, 31],
       [56, 67,  8, 97, 21]])

In [40]:
randint(0,3,5)

array([2, 2, 1, 2, 0])

In [44]:
coba = randint(0,10,20).reshape(5,4)

In [45]:
coba

array([[0, 5, 1, 2],
       [9, 2, 7, 5],
       [7, 7, 3, 3],
       [6, 1, 6, 2],
       [8, 7, 4, 0]])

In [50]:
coba = coba.reshape(2,10)

In [51]:
coba

array([[0, 5, 1, 2, 9, 2, 7, 5, 7, 7],
       [3, 3, 6, 1, 6, 2, 8, 7, 4, 0]])

In [53]:
coba1d = randint(0,100,20)

In [54]:
coba2d = randint(0,100,20).reshape(4,5)

In [55]:
coba1d

array([39, 21, 52, 96, 75, 21, 25, 76, 78, 48, 88,  0, 86, 18, 52, 35,  5,
       33, 27,  0])

In [56]:
coba2d

array([[91, 60, 37, 99, 74],
       [21, 73, 94, 84, 22],
       [33, 74, 66, 23, 83],
       [81, 42, 53, 71, 75]])

In [57]:
#menunjukan angka tertinggi
coba1d.max()

96

In [58]:
#menunjukan angka tertinggi
coba2d.max()

99

In [59]:
#menunjukan angka terendah
coba1d.min()

0

In [60]:
#menunjukan angka terendah
coba2d.min()

21

In [61]:
#index yang menunjukan urutan dimana angka tertinggi
coba2d.argmax()

3

In [62]:
#index yang menunjukan urutan dimana angka terendah
coba2d.argmin()

5

In [63]:
#mengidentifikasi bentuk matriks
coba1d.shape

(20,)

In [64]:
#mengidentifikasi bentuk matriks
coba2d.shape

(4, 5)

In [66]:
#mengidentifikasi tipe
coba1d.dtype

dtype('int32')

In [67]:
#mengidentifikasi tipe
coba2d.dtype

dtype('int32')

In [88]:
#index dalam numpy
coba = np.arange(0,11)
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
#mengambil angka dengan urutan ke-
coba[6]

6

In [90]:
#mengambil semua angka dimulai dari urutan ke- 
coba[5:]

array([ 5,  6,  7,  8,  9, 10])

In [91]:
#mengambil semua angka hingga urutan ke- 
coba[:5]

array([0, 1, 2, 3, 4])

In [92]:
#mengambil semua angka dari dan hingga 
coba[5:9]

array([5, 6, 7, 8])

In [94]:
coba[2:5]

array([2, 3, 4])

In [95]:
#mengambil semua angka dari dan hingga dengan variabel baru 
coba2 = coba[5:9]

In [96]:
coba2

array([5, 6, 7, 8])

In [97]:
#merubah semua nilai  
coba2[:] = 100

In [98]:
coba2

array([100, 100, 100, 100])

In [99]:
#perubahan nilai mempengaruhi nilai di variabel sebelumnya 
coba

array([  0,   1,   2,   3,   4, 100, 100, 100, 100,   9,  10])

In [100]:
#solusi agar tidak merubah variabel awal 
coba3 = coba.copy()

In [101]:
coba3[:] = 200

In [102]:
coba3

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [103]:
coba

array([  0,   1,   2,   3,   4, 100, 100, 100, 100,   9,  10])

In [105]:
bilangan2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [106]:
bilangan2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
bilangan2d[0,0]

1

In [113]:
bilangan2d[1]

array([4, 5, 6])

In [112]:
bilangan2d[2,2]

9

In [114]:
bilangan2d[1:2,1:]

array([[5, 6]])

## Slicing dengan Boolean pada Numpy

In [129]:
bil = np.arange(1,11)
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
#justifikasi nilai
angka = bil>5
angka

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [131]:
#merubah menjadi array
bil = bil[angka]
bil

array([ 6,  7,  8,  9, 10])

In [132]:
bil = bil[bil>5]
bil

array([ 6,  7,  8,  9, 10])

## Operasi Numpy

In [134]:
import numpy as np

In [135]:
test = np.arange(0,11)

In [136]:
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
test+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [138]:
test+test

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [139]:
test_list = [0,1,2,3,4,5,6,7,8,9,10]

In [140]:
test_list+test_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [141]:
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
test*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [144]:
test_list*3

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

In [146]:
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
test-test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [148]:
test-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [150]:
test/test

<ipython-input-150-555f4e4015d6>:1: RuntimeWarning: invalid value encountered in true_divide
  test/test


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [152]:
1/test

<ipython-input-152-9bdc9f62f56d>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/test


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [153]:
np.sqrt(test)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [154]:
np.exp(test)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [155]:
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
np.min(test)

0

In [157]:
np.max(test)

10

In [158]:
np.sin(test)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [159]:
np.log(test)

<ipython-input-159-4cb59cfe15dc>:1: RuntimeWarning: divide by zero encountered in log
  np.log(test)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [16]:
arr= np.array([ [ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])